version: 1
tests:
  contractTests:
    - openApiOperation: '*::/*'
      statusSuccess:
        enabled: true
    - openApiOperation: '*::/*'
      responseTime:
        enabled: false
        maxMs: 300
    - openApiOperation: '*::/*'
      excludeForOperations:
        - images
      contentType:
        enabled: true
    - openApiOperation: '*::/*'
      jsonBody:
        enabled: true
    - openApiOperation: '*::/*'
      schemaValidation:
        enabled: true
    - openApiOperation: '*::/*'
      headersPresent:
        enabled: true
  contentTests: []
  extendTests: []
  variationTests:
    - openApiOperation: 'GET::/cardinfo.php'
      openApiResponse: '200'
      variations:
        - name: 'Misc parameter'
          overwrites:
            - overwriteRequestQueryParams:
              - key: misc
                value: 'yes'
                overwrite: true
                disable: false
          tests:
            contractTests:
              - statusSuccess:
                  enabled: true
              - responseTime:
                  enabled: false
                  maxMs: 300
              - contentType:
                  enabled: true
              - jsonBody:
                  enabled: true
              - schemaValidation:
                  enabled: true
              - headersPresent:
                  enabled: true
assignVariables: []
overwrites: []
globals:
  stripResponseExamples: true
  collectionPreRequestScripts: []
  keyValueReplacements: {}
  valueReplacements: {}
  rawReplacements: []
  portmanReplacements:
    - searchFor: '"last_update":{"type":"string","format":"date-time"}'
      replaceWith: '"last_update":{"type":"string"}'
