openapi: 3.0.3
info:
  title: YGOPRODeck API
  version: v7
  termsOfService: https://ygoprodeck.com/api-guide/
  # license object is REQUIRED by redoc
  license:
    name: Unknown
    url: https://ygoprodeck.com/about/
  description: |
    This is a third-party project to document for developers the [Yu-Gi-Oh! API by YGOPRODeck](https://ygoprodeck.com/api-guide/).
    Please, visit the site for the official documentation.
    
    This is the description based on the last update (24th January 2023).
servers:
  - url: https://db.ygoprodeck.com/api/v7
externalDocs:
  url: https://ygoprodeck.com/api-guide/
tags:
  - name: database
    description: Database API
  - name: images
    description: Images API

paths:
  /cardinfo.php:
    $ref: './paths/cardinfo.yaml'
  /checkDBVer.php:
    $ref: './paths/checkDBVer.yaml'
  /cardsets.php:
    $ref: './paths/cardsets.yaml'
  /archetypes.php:
    $ref: './paths/archetypes.yaml'
  /cardsetsinfo.php:
    $ref: './paths/cardsetsinfo.yaml'
  /randomcard.php:
    $ref: './paths/randomcard.yaml'
  /images/cards/{id}.jpg:
    $ref: './paths/images_cards.yaml'
  /images/cards_small/{id}.jpg:
    $ref: './paths/images_cards_small.yaml'
  /images/cards_cropped/{id}.jpg:
    $ref: './paths/images_cards_cropped.yaml'
  /images/sets/{set_code}.jpg:
    $ref: './paths/images_sets.yaml'