name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # creates the bundle
      - name: Build
        run: make build

      # create the postman json and run tests
      - name: Test
        run: make test
      
      # upload the artifact to the workflow
      - name: Upload Distribution
        uses: actions/upload-artifact@v3.1.2
        with:
          name: distribution
          path: dist
          if-no-files-found: error
